### ISSUE TITLE
Compatibility with JDK17

### ISSUE THREAD

**Issue by johnmax132** [anthonygauthier/jmeter-elasticsearch-backend-listener#125]
Hello,
When I use JDK17 with Jmeter, I have this error log : 
 
`java.lang.IncompatibleClassChangeError: class com.google.common.collect.RegularImmutableSortedMap cannot inherit from final class com.google.common.collect.ImmutableSortedMap

    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]

    at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]

    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]

    at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]

    at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]

    at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]

    at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]

    at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]

    at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]

    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]

    at java.lang.Class.forName0(Native Method) ~[?:?]

    at java.lang.Class.forName(Class.java:467) ~[?:?]

    at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.isChildOf(ClassFinder.java:198) ~[jorphan.jar:5.6.2]

    at org.apache.jorphan.reflect.ClassFinder$ExtendsClassFilter.accept(ClassFinder.java:184) ~[jorphan.jar:5.6.2]

    at org.apache.jorphan.reflect.ClassFinder.applyFiltering(ClassFinder.java:541) ~[jorphan.jar:5.6.2]

    at org.apache.jorphan.reflect.ClassFinder.lambda$findClassesInOnePath$2(ClassFinder.java:501) ~[jorphan.jar:5.6.2]

    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]

    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]

    at java.util.zip.ZipFile$EntrySpliterator.tryAdvance(ZipFile.java:558) ~[?:?]

    at java.util.Spliterator.forEachRemaining(Spliterator.java:332) ~[?:?]

    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]

    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]

    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]

    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]

    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]

    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]

    at org.apache.jorphan.reflect.ClassFinder.findClassesInOnePath(ClassFinder.java:499) ~[jorphan.jar:5.6.2]

    at org.apache.jorphan.reflect.ClassFinder.findClasses(ClassFinder.java:443) ~[jorphan.jar:5.6.2]

    at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:413) ~[jorphan.jar:5.6.2]

    at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:336) ~[jorphan.jar:5.6.2]

    at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:315) ~[jorphan.jar:5.6.2]

    at org.apache.jorphan.reflect.ClassFinder.findClassesThatExtend(ClassFinder.java:282) ~[jorphan.jar:5.6.2]

    at org.apache.jmeter.gui.util.MenuFactory.initializeMenus(MenuFactory.java:130) ~[ApacheJMeter_core.jar:5.6.2]

    at org.apache.jmeter.gui.util.MenuFactory.<clinit>(MenuFactory.java:107) ~[ApacheJMeter_core.jar:5.6.2]

    at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:101) ~[ApacheJMeter_core.jar:5.6.2]

    at org.apache.jmeter.gui.tree.JMeterTreeNode.createPopupMenu(JMeterTreeNode.java:184) ~[ApacheJMeter_core.jar:5.6.2]

    at org.apache.jmeter.gui.action.EditCommand.doAction(EditCommand.java:49) ~[ApacheJMeter_core.jar:5.6.2]

    at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:83) ~[ApacheJMeter_core.jar:5.6.2]

    at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:65) ~[ApacheJMeter_core.jar:5.6.2]

    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) [?:?]

    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) [?:?]

    at java.awt.EventQueue$4.run(EventQueue.java:722) [?:?]

    at java.awt.EventQueue$4.run(EventQueue.java:716) [?:?]

    at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]

    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]

    at java.awt.EventQueue.dispatchEvent(EventQueue.java:741) ~[?:?]

    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]

    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]

    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117) ~[?:?]

    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191) ~[?:?]

    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236) ~[?:?]

    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234) ~[?:?]

    at java.security.AccessController.doPrivileged(AccessController.java:318) [?:?]

    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234) ~[?:?]

    at java.awt.Dialog.show(Dialog.java:1080) ~[?:?]

    at java.awt.Component.show(Component.java:1728) ~[?:?]

    at java.awt.Component.setVisible(Component.java:1675) ~[?:?]

    at java.awt.Window.setVisible(Window.java:1036) ~[?:?]

    at java.awt.Dialog.setVisible(Dialog.java:1016) ~[?:?]

    at org.apache.jmeter.SplashScreen.lambda$showScreen$0(SplashScreen.java:95) ~[ApacheJMeter_core.jar:5.6.2]

    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]

    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) ~[?:?]

    at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]

    at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]

    at java.security.AccessController.doPrivileged(AccessController.java:399) [?:?]

    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) [?:?]

    at java.awt.EventQueue.dispatchEvent(EventQueue.java:741) [?:?]

    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]

    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]

    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]

    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]

    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]

    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?] `

I had no problem with JDK11, is this plugin compatible with JDK 17 ?

**Comment by anthonygauthier** [comment]
There most likely are compatibility issues with this as the plugin was developed back when JDK9 was still pretty hot 😂.

I'm resuming work on this so I'll give it a look
